- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install Java 17
  ansible.builtin.apt:
    name: 
      - openjdk-17-jdk
      - openjdk-17-jre
    state: present
